# Automatically generated by Terraform
# Manual changes will be lost

config dnsmasq
        option domainneeded '1'
        option localise_queries '1'
        option rebind_protection '1'
        option rebind_localhost '1'
        option local '/lan/'
        option domain 'lan'
        option expandhosts '1'
        option authoritative '1'
        option readethers '1'
        option leasefile '/tmp/dhcp.leases'
        option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
        option localservice '1'
        option ednspacket_max '1232'
        option confdir '/tmp/dnsmasq.d'
        option dnsforwardmax '1500'
        option min_cache_ttl '270'
        option cachesize '5000'
        list rebind_domain 'angelnu.com'
        list rebind_domain 'home.angelnu.com'
        list rebind_domain 'casa96.angelnu.com'
        list rebind_domain 'plex.direct'
        list rebind_domain 'nunez-gregoire.eu'
        list rebind_domain 'home.nunez-gregoire.eu'
        list rebind_domain 'pub.angelnu.com'
        list address '/pub.angelnu.com/192.168.1.128'
        list address '/router/192.168.2.1'

config dhcp 'lan'
        option interface 'lan'
        option limit '150'
        option leasetime '96h'
        option start '538'
        list ra_flags 'none'

config dhcp 'wan'
        option interface 'wan'
        option ignore '1'
        list ra_flags 'none'

config odhcpd 'odhcpd'
        option maindhcp '0'
        option leasefile '/tmp/hosts/odhcpd'
        option leasetrigger '/usr/sbin/odhcpd-update'
        option loglevel '4'

%{ for client in clients ~}
%{ if client.type == "host" ~}
config host
        option name '${client.name}'
%{ if client.ip != "" ~}
        option ip '${client.ip}'
%{ endif ~}
%{ if client.mac != "" ~}
        option mac '${client.mac}'
%{ endif ~}
%{ if client.isDNS != "" ~}
        option dns '${client.isDNS}'
%{ endif ~}
%{ endif ~} 
%{ if client.type == "domain" ~}
config domain
        option name '${client.name}'
%{ if client.ip != "" ~}
        option ip '${client.ip}'
%{ endif ~}
%{ endif ~} 
%{ endfor ~} 
